diffusion:
  T: 1000
  beta_start: 0.0001
  beta_stop: 0.01

arch:
  model: Maria
  width_mult: 32
  timestep_channels: 8
  diffusion_method: linear

optim:
  lr: 0.0001
  weight_decay: 0.0

training:
  batch_size: 16
  log_freq: 10
  checkpoint_freq: 1000
  persist_freq: 50
  metrics_freq: 5
  metrics_ema_alpha: 0.9
  ema_alpha: 0.995
  ema_freq: 20

wandb:
  enable: true
  log_freq: 10
  img_freq: 100
  img_n: 8
  img_show_bar: true
  gradient_freq: 100
  project: noisy
  group: birds
  name: null
  tags: [birds, rgb, size_64x64, local, width_32]

img:
  size: 128
  channels: 3

data:
  path: ../../common/data/birds/
  extensions:
    - .jpeg
    - .jpg
    - .png
