T: 256

arch:
  width_mult: 32
  timestep_channels: 5

optim:
  lr: 0.001
  weight_decay: 0.01

training:
  batch_size: 32
  log_freq: 10
  checkpoint_freq: 500
  metrics_freq: 5
  steps: 2

wandb:
  enable: true
  log_freq: 10
  img_freq: 100
  gradient_freq: 100
  project: noisy
  group: birds
  name: null
  tags: [birds, rgb, size_64x64, local, width_32]

img:
  size: 64
  channels: 3

data:
  path: ./data/birds/
  extensions:
    - .jpeg
    - .jpg
    - .png
