diffusion:
  T: 1000
  beta_start: 0.0001
  beta_stop: 0.01

arch:
  width_mult: 64
  timestep_channels: 16

optim:
  lr: 0.0001
  weight_decay: 0.0

training:
  batch_size: 7
  log_freq: 10
  checkpoint_freq: 2000
  metrics_freq: 5

wandb:
  enable: true
  log_freq: 10
  img_freq: 1000
  img_n: 4
  img_show_bar: true
  gradient_freq: 100
  project: noisy
  group: birds
  name: lara-local
  tags: [birds, rgb, size_64x64, local, width_64]

img:
  size: 128
  channels: 3

data:
  path: ./data/birds/
  extensions:
    - .jpeg
    - .jpg
    - .png
