diffusion:
  T: 1000
  beta_start: 0.0001
  beta_stop: 0.01

arch:
  width_mult: 64
  timestep_channels: 16

optim:
  lr: 0.0001
  weight_decay: 0.0001

training:
  batch_size: 32
  log_freq: 10
  checkpoint_freq: 2000
  persist_freq: 50
  metrics_freq: 5
  ema_alpha: 0.995
  ema_freq: 20

wandb:
  enable: true
  log_freq: 10
  img_freq: 2000
  img_n: 8
  img_show_bar: false
  gradient_freq: 500
  project: noisy
  group: birds
  name: lara
  tags: [birds, rgb, size_128x128, viking, width_64]

img:
  size: 128
  channels: 3

data:
  path: ../data/birds/
  extensions:
    - .jpeg
    - .jpg
    - .png
