T: 1000

arch:
  width_mult: 32
  timestep_channels: 5

optim:
  lr: 0.001
  weight_decay: 0.01

training:
  batch_size: 128
  log_freq: 10
  checkpoint_freq: 1000
  steps: 2

wandb:
  enable: true
  log_freq: 50
  gradient_freq: 50
  project: noisy
  group: birds
  name: nora
  tags: [birds, rgb, size_64x64, viking, width_32]

img:
  size: 64
  channels: 3

data:
  path: ../data/birds/
  extensions:
    - .jpeg
    - .jpg
    - .png
